name: Validate Files
on:
  push:
    branches: [main]
    paths: ['diffs/**/*.json']
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install jsonschema
      - name: Validate diff files
        run: |
          echo "Looking for diff files to validate..."
          for file in diffs/*.json; do
            if [ -f "$file" ]; then
              echo "Validating: $file"
              python scripts/validate_diff.py "$file"
            fi
          done
          echo "Validation complete"
